#!/usr/sbin/nft -f

flush ruleset

table inet filter {
  set lan_v4 {
    type ipv4_addr
    flags interval
    elements = { 192.168.32.0/20 }
  }

  chain input {
    type filter hook input priority 0;
    policy drop;

    iif "lo" accept
    ct state established,related accept

    ip saddr @lan_v4 tcp dport { 53, 8080 } accept
    ip saddr @lan_v4 udp dport { 53 } accept

    ip saddr @lan_v4 tcp dport 22 accept

    counter drop
  }

  chain forward {
    type filter hook forward priority 0;
    policy drop;
  }

  chain output {
    type filter hook output priority 0;
    policy accept;
  }
}
