FROM docker.io/library/debian:13-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends unbound ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY unbound.conf /etc/unbound/unbound.conf

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["unbound", "-d", "-c", "/etc/unbound/unbound.conf"]
